version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: music_gpt_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: music_gpt
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: music_gpt_redis
    restart: always
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: music_gpt_api
    restart: always
    ports:
      - '8080:3000'
    env_file:
      - .env  
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/music_gpt
      REDIS_URL: redis://redis:6379
      # JWT_SECRET: EgikWXIqmVLLWCz1aNckt8RJOrEvE6BjE2J9UHBFuuYwHGiDWIQrG0Ji+wBjYr0M8ENzj9Xc++EobN26UW/EWA==
      # JWT_REFRESH_SECRET: mw25nmvD7bmEd+wNOaw1YAORbANXy0w7YHcXYBfkESpbKk3EM/0Q+j3fG/HRrFDonAbD1E+TBMGnYj3fkjFWYA==
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: music_gpt_worker
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/music_gpt
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data: